#!/bin/bash
echo TEST_NAME=$TEST_NAME
echo "Launching $TEST_N_PVCAPTURE $TEST_APPTYPE IOCs w/ $TEST_N_COUNTERS Counters each"
echo TEST_PVCAPTURE_BASEPORT=$TEST_PVCAPTURE_BASEPORT
echo TEST_CIRCBUFF_SIZE=$TEST_CIRCBUFF_SIZE
echo TEST_COUNTER_RATE=$TEST_COUNTER_RATE
echo TEST_COUNTER_DELAY=$TEST_COUNTER_DELAY
echo TEST_DRIVE=$TEST_DRIVE
echo TEST_EPICS_PVA_SERVER_PORT=$TEST_EPICS_PVA_SERVER_PORT
echo TEST_EPICS_PVA_BROADCAST_PORT=$TEST_EPICS_PVA_BROADCAST_PORT
echo TEST_PV_PREFIX=$TEST_PV_PREFIX
echo TEST_N_LOADSERVERS=$TEST_N_LOADSERVERS
echo N_CNT_PER_SERVER=$N_CNT_PER_SERVER
echo N_PVS_PER_CLIENT=$N_PVS_PER_CLIENT

echo Start: `date`
uname -a > $TEST_HOST_DIR/uname.info
cat /proc/cpuinfo > $TEST_HOST_DIR/cpu.info
cat /proc/meminfo > $TEST_HOST_DIR/mem.info
cat /proc/loadavg > $TEST_HOST_DIR/loadavg.info

